import Head from "next/head";
import styles from "@/styles/Home.module.css";

import useSWR from 'swr'


// To be updated with the Amazon CloudFront distribution domain deployed through the CloudFormation Template
// You can view this domain in the 'Output' tab of your CloudFormation stack deployment
const APIEndPoint = process.env.API_ENDPOINT;

export default function Home() {
  return (
    <>
      <Head>
        <title>Demo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>

          <p>This react-based single page application (SPA) is hosted in an Amazon S3 bucket exposed through an Amazon CloudFront distribution.</p>
          <p>It calls an API configured in Amazon API Gateway and exposed through the same Amazon CloudFront distribution as the application.</p>

          <HelloWorld/>

          </main>
      </div>
    </>
  );
}

const fetcher = (url:string) => fetch(url).then((res) => res.json());

function HelloWorld() {
  const { data, error } = useSWR(APIEndPoint, fetcher)
 
  if (error) return <div>Failed to call REST API: {error.message}</div>
  if (!data) return <div>Loading...</div>
 
  return (
    <div>{data.message}</div>
  )
}